# Define if we use ASIC post-synthesis simulation (0: pre-synth, 1:post-synth)
export USE_ASIC_POST_SYN = 0

# Define the VCS Verilog CARGS
# export SIM_CARGS_VERILOG = -full64 -nc \
# 	-y /afs/slac/g/reseng/synopsys/syn/P-2019.03-SP3/dw/sim_ver \
# 	-y /afs/slac.stanford.edu/g/airic/cad/cadence/GENUS_20.10.000_lnx86/share/synth/lib/chipware/sim/verilog/CW \
# 	+libext+.v+.sv+

# Use top level makefile
include ../shared_config.mk
include ../../submodules/ruckus/system_vivado.mk
