import sys
import os
import click
import argparse
import time

top_level = os.path.realpath(__file__).split('software')[0]
sys.path.append(top_level+'firmware/python/')

import pix2pgp

# Set the argument parser
parser = argparse.ArgumentParser()

parser.add_argument(
    "--dataFile",
    type     = str,
    required = False,
    default  = '../firmware/ghdl/pix2pgpAxiDataDump.dat',
    help     = "Default data file",
)

parser.add_argument(
    "--rawData",
    action   ="store_true",
    help     = "Set to true if data are generated by FPGA testbench data generator",
)

parser.add_argument(
    "--asicType",
    type     = str,
    required = False,
    default  = 'SparkPixS',
    help     = "options: SparkPixS, SparkPixT, Thriglav",
)

parser.add_argument(
    "--verbose",
    type     = int,
    required = False,
    default  = 0,
    help     = "Verbosity level: 0 = no printing, 1 = errors only, 2, 3, 4 varying levels of info.",
)

# Get the arguments
args = parser.parse_args()

#################################################################
if __name__ == "__main__":
    _file = args.dataFile

    if not(os.path.isfile(_file)):
        click.secho(f"[ERROR]: {_file} not found!", bg='red')
        sys.exit()

    with open(_file) as f:
        _dataArray = [int(line.rstrip('\n'), 16) for line in f]

    _fileSize = len(_dataArray)
    asicLaneValid = [[] for _ in range(4)]
    asicHits      = [[] for _ in range(4)]
    asicTrgCnt    = [[] for _ in range(4)]


    asicDecoder = pix2pgp.AsicData(asicType=args.asicType,
                                   rawData=args.rawData,
                                   verbose=args.verbose)

    asicDecoder.formatter(data=_dataArray, dataLen=_fileSize)

    _asicId = asicDecoder.asicId

    asicLaneValid[_asicId].append(asicDecoder.laneValid.copy())
    asicHits[_asicId].append(asicDecoder.asicHits.copy())
    asicTrgCnt[_asicId].append(asicDecoder.asicGlblTrgCnt.copy())
