#####################################################################################################
Root:
  enable: True
  ForceWrite: False
  InitAfterConfig: False
  PollEn: False
  #####################################################################################################
  App:
    enable: True
    #####################################################################################################
    # Pix2PgpEmuCtrl:
